package com.mortgageinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("credit rating")
	private java.lang.Double creditRating;

	@org.kie.api.definition.type.Label("approved")
	private java.lang.Boolean approved;

	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;

	public Customer() {
	}

	public java.lang.Double getCreditRating() {
		return this.creditRating;
	}

	public void setCreditRating(java.lang.Double creditRating) {
		this.creditRating = creditRating;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Customer(java.lang.Double creditRating, java.lang.Boolean approved,
			java.lang.Integer age) {
		this.creditRating = creditRating;
		this.approved = approved;
		this.age = age;
	}

}