package com.mortgageinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MortgageApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MortgageApplication() {
    }




}